name: Install, Build & Check

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  install-build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: |
          pnpm run build

      - name: Check "dist" Directory
        run: |
          if [ -d "dist" ]; then
            echo "Directory exists"
          else
            echo "Directory does not exist"
            exit 1
          fi
