name: Install & Check

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  install-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Check Build Commands (Optional)
        run: |
          pnpm --filter frontend build
          pnpm --filter backend build
